# Generated by Django 2.2.1 on 2019-07-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, default=0, verbose_name='id')),
                ('maker', models.CharField(max_length=255, verbose_name='maker')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
    ]
