# Generated by Django 2.2.1 on 2019-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='no',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
